FROM elasticsearch:6.8.4

MAINTAINER zhangmengjie "zhangmengjie@gmail.com"

RUN ./bin/elasticsearch-plugin install --batch https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.8.4/elasticsearch-analysis-ik-6.8.4.zip